# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Oscar Infante
title: Scientific on pesticides
email: oscar.infmon@gmail.com
website: https://alexei-im.github.io/Prueba_CV/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  alexei-im
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: alexei_im
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0002-8591-4567

# Additional icon links
additional_links:
- title: ibt.unam.mx
  icon: fas fa-globe
  url: https://ibt.unam.mx/perfil/6453/oscar-alexei-infante-montano
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Oscar and I'm a future scientist with a master's degree on biochemistry, focused on Bt proteins and their insecticidal effect.

  I am most skilled in: <mark>Molecular techniques</mark> and <mark>Bioinformatic analysis</mark>
content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Identification of the interaction sites of the Vip3Aa toxin with its receptors in Spodoptera frugiperda
        link: link_de_la_publicacion_o_doi
        # link_text: Project Website
        additional_links:
          - title:  Revista donde se publico
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Publicacion resultado de mi proyecto de maestria
        description: | # this will include new lines to allow paragraphs
          Despues de dos anos de largo esfuerzo se consiguio la publicacion de este articulo donde yo no escribi ni vergas ahuevo que si.
      - layout: top-middle
        title: Proyecto con Minhui
        link: link_de_la_publicacion_o_doi
        link_text: Project Website
        additional_links:
          - title:  Revista donde se publico esta wuea
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
            # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            #   icon: fab fa-github
            #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Esta publicacion la realice en el AGIS
        description: | # this will include new lines to allow paragraphs
          Durante mi primer estancia internacional y como parte de mis estudios de maestria realice un numero de experimentos que fueron esenciales para la corroboracion de esta investigacion        
      - layout: top-middle
        title: Proyecto con ZouLoumin
        link: link_de_la_publicacion_o_doi
        # link_text: Project Website
        additional_links:
          - title:  Revista donde se publico esta wuea
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
            # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            #   icon: fab fa-github
            #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Esta publicacion la realice en el AGIS
        description: | # this will include new lines to allow paragraphs
          Durante mi primer estancia internacional y como parte de mis estudios de maestria realice un numero de experimentos que fueron esenciales para la corroboracion de esta investigacion

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Coding
        quote: >
            Python, R, Perl, bash, MySQL, C and Matlab
      - layout: top-middle
        title: Bioinformatics
        quote: >
            Genome assembly, Genome annotation, Metagenomics, Transcriptomic  analysis, Machine learning, Gene ontology, Phylogenetic, Protein structure, Databases, Parsing, Plotting, Regulatory networks.
      - layout: top-middle
        title: Molecular techniques
        quote: >
            PCR, mutagenesis, protein expression, purification, binding assays, western blot, restriction enzymes.
  
                
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Nacional Autonoma de Mexico, UNAM
        caption: 2022 - 2024
        sub_title: M.S. Biochemical Sciences
        quote: >
          The graduate program in Biochemical Sciences offered by UNAM, recognized as a high-quality program by CONACYT, aims to train master's and doctoral students in science with exceptional academic standards.
        description: | # this will include new lines to allow paragraphs
          During my master's studies, I focused on characterizing the Vip3Aa toxin. To strengthen my prior knowledge, I enrolled in courses on protein structures. Additionally, during my master's program, I undertook a research internship with Dr. Xiao Yutao at the Agriculture Genomic Institute of Shenzhen, China. There, I engaged in various projects on the interaction between the Vip3Aa protein and potential receptors, participating in the planning of experiments that demonstrated the binding of these receptors to the toxin.
      - layout: left
        title: Universidad Nacional Autonoma de Mexico, UNAM
        caption: 2017 - 2021
        sub_title: B.Sc. in Genomic Sciences
        quote: >
          The Bachelor’s degree in Genomic Sciences was established by UNAM in 2002 with the intention of creating a specialized program focused on a new era in biology: genomics.
        description: | # this will include new lines to allow paragraphs
          In the bachelor's program, most of my courses focused on bioinformatics, biology, and mathematics, making me well-versed in these three areas of study. Additionally, during my undergraduate studies, I organized scientific outreach events and served as a teaching assistant for various courses.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
